### ISSUE TITLE
지원하는 법정 화폐 종류 늘리기

### ISSUE THREAD

**Issue by dqdq4197** [dqdq4197/BitFolio-app#15]
### 1차 법정 화폐 종류 늘리기

기축 통화 3가지
- aud : 호주 달러
- cny: 중국
- ars: 아르헨티나

--------
암호 화폐 3가지
- btc
- eth
- usdt

### TODO
- [ ] 해당 통화에 맞는 formater 구현
- [ ] base type -> currency에 타입 추가
- [ ] 설정 탭에 선택란 추가
