### ISSUE TITLE
firebase 연결 & authentication 구현

### ISSUE THREAD

**Issue by dqdq4197** [dqdq4197/BitFolio-app#34]
### TODO

- [x] firebase config 설정 & sdk 연결 

### 회원 가입
- [ ] 본인 인증 메일 발송 안내 모달 작성
- [ ] 정상 가입시 home으로 redirect & 가입 환영 모달?
- [ ] submit 로딩 & 에러 처리

#### 예외 처리
- [ ]  이미 존재하는 회원
-------------------
### 로그인
- [ ] 정상 로그인 home으로 redirect
- [ ] submit 로딩 & 에러 처리

#### 예외 처리
- [ ]  존재하지 않은 유저 정보 입력시 안내
------------------
### config
- [ ] AppLoader에서 authenticated check 
- [ ] 회원 가입 메일 승인시 앱으로 redirect
----------------
### next move 
- firebase send mail 도메인 주소 바꾸기
- 내 정보 페이지 생성
- 추가 소셜 로그인 & 회원 가입
  - 구글
  - 애플
  - 페이스북?
